---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go version
---
kind: signature
hmac: 04b72fe2f49995dcb0d54e959aade920c08cdc5824cfbf75b8db8e4526effd6a

...
