---
kind: pipeline
name: main

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: grafana/grafana-build
    tags:
    - latest
    - main

trigger:
  event:
  - push
  branch:
  - main
---
kind: signature
hmac: 66f31f76fd7902b2ae6dca34ba027671f8fd091175e626e71f3f6de5452ae5be

...
